document.write("<h1>Title : 외부 자바스크립트 파일 사용하기</h1>")
document.write("<h1>Test</h1>")
document.write("<p>Test Message</p>")
document.write("<p>script 테그 src속성에 경로를 입력하면 해당 경로에 있는</p>")
document.write("<p>파일을 불러와서 script를 실행한다.</p>")